# Site settings
title: Patrick Jiang
description: This is Patrick Jiang Resume Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Patrick Jiang
user_description: Highly motivated student on 3rd year of Business Information Technology in Red River College. Proficient with multiple programming languages including C/C++/C#, Ruby, Javascript/JQuery, HTML and CSS for both web and desktop application development. Experienced with various operating systems including Linux with UNIX command and Windows. Energetic and passionate about programming and capable of working in a fast-paced environment as well as multi-tasking.
user_title: Junior Developer
email: patrick_jiang86@hotmail.com
# twitter_username: lorem_ipsum
github_username: Patrick-Jiang
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
